apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.port }}
    - name: ws
      port: {{ .Values.service.backend.wsPort }}
      targetPort: {{ .Values.service.backend.wsPort }}
