apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount.backend }}
  progressDeadlineSeconds: 800
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: mongo:7
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_INITDB_ROOT_PASSWORD
          command:
            - sh
            - -c
            - |
              until mongosh --host mongodb-service --port {{ .Values.service.mongodb.port }} \
                -u "$MONGO_USER" -p "$MONGO_PASS" --authenticationDatabase admin \
                --eval "db.adminCommand('ping')" --quiet 2>/dev/null; do
                echo "Waiting for MongoDB to be ready..."; sleep 5
              done
              echo "MongoDB ready."
      containers:
        - name: backend
          image: "{{ .Values.image.backend.name }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.backend.port }}
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          volumeMounts:
            - name: reports-storage
              mountPath: /app/reports
          resources:
            requests:
              memory: {{ .Values.resources.backend.requests.memory | quote }}
              cpu: {{ .Values.resources.backend.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.backend.limits.memory | quote }}
              cpu: {{ .Values.resources.backend.limits.cpu | quote }}
          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.backend.port }}
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.backend.port }}
            initialDelaySeconds: 0
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.backend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: reports-storage
          persistentVolumeClaim:
            claimName: backend-pvc
