apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Release.Namespace }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv }}
  PORT: {{ .Values.config.port | quote }}
  MONGODB_HOST: {{ .Values.config.mongodbHost }}
  MONGODB_PORT: {{ .Values.config.mongodbPort | quote }}
  MONGODB_DB: {{ .Values.config.mongodbDb }}
  ALLOWED_ORIGIN: {{ .Values.config.allowedOrigin }}
