apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: mongodb-headless
  replicas: {{ .Values.replicaCount.mongodb }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      automountServiceAccountToken: false
      containers:
        - name: mongodb
          image: "{{ .Values.image.mongodb.name }}:{{ .Values.image.mongodb.tag }}"
          imagePullPolicy: {{ .Values.image.mongodb.pullPolicy }}
          command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
          ports:
            - containerPort: {{ .Values.service.mongodb.port }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.config.mongodbDb }}
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
          resources:
            requests:
              memory: {{ .Values.resources.mongodb.requests.memory | quote }}
              cpu: {{ .Values.resources.mongodb.requests.cpu | quote }}
              ephemeral-storage: "500Mi"
            limits:
              memory: {{ .Values.resources.mongodb.limits.memory | quote }}
              cpu: {{ .Values.resources.mongodb.limits.cpu | quote }}
              ephemeral-storage: "1Gi"
          readinessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: mongodb-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.mongodb.size }}
