apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: {{ .Values.service.mongodb.port }}
      targetPort: {{ .Values.service.mongodb.port }}
