replicaCount:
  backend: 2
  frontend: 1
  mongodb: 1

image:
  backend:
    name: telnet-backend
    tag: latest
    pullPolicy: Never
  frontend:
    name: telnet-frontend
    tag: latest
    pullPolicy: Never
  mongodb:
    name: mongo
    tag: "7"
    pullPolicy: IfNotPresent

service:
  backend:
    port: 3002
  frontend:
    port: 80
  mongodb:
    port: 27017

ingress:
  host: telnet-app.local

config:
  nodeEnv: production
  port: "3002"
  mongodbHost: mongodb-service
  mongodbPort: "27017"
  mongodbDb: telnet-db
  allowedOrigin: "http://localhost:3000,http://localhost:8080"

secrets:
  jwtSecret: "CHANGE_ME"
  mongodbUri: "CHANGE_ME"
  mongoRootUsername: "CHANGE_ME"
  mongoRootPassword: "CHANGE_ME"

persistence:
  backend:
    size: 1Gi
  mongodb:
    size: 2Gi

resources:
  backend:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "300m"
  frontend:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  mongodb:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"
