apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: telnet-app
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
---
# Service headless pour la resolution DNS inter-pods du StatefulSet
# Adresse chaque pod : mongodb-0.mongodb-headless, mongodb-1.mongodb-headless...
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: telnet-app
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
