service:
  type: NodePort

adminPassword: admin123

persistence:
  enabled: true
  size: 1Gi
  storageClassName: standard

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
