apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: telnet-app
type: Opaque
stringData:
  JWT_SECRET: "telnet-jwt-secret-2024"
  MONGO_URI: "mongodb://admin:admin123@mongodb-0.mongodb-headless:27017,mongodb-1.mongodb-headless:27017,mongodb-2.mongodb-headless:27017/telnet-db?authSource=admin&replicaSet=rs0"
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "admin123"
